hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b16906634dc8b2a07d43cdc6ba766e642e18458f7e7b9aaef8a374e5e7fd04dc"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "3d901343bdcb30f4abcbf8801c2bef2f2fa1921dc4f4fca0ea445e989c353b24"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "e65f1856eed8725712eb26dd607cbed73de44b430bb069ba543ff706b35b2603"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "518e512a141b3b331ecaafaf315a9636f9eadf211c0df39395109e8dbf588a54"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "4b8846c188d33f4d99bd78d227ad9324bb83aea6900d4199f13288dda49d15a3"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6be7edd9b88632678b25f96b46c1cb79dcc0d92f7165dee84421661b50683090"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/packwiz-server-updater.pw.toml"
hash = "90397481159d6f8c13f811b930a4020c7e24c62e35e3cc3596164d312fb0372c"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "d22546ad55b555931eb527f163b3564e00c12c7dc8101378b87447dfcc8e0652"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "08d4775f8546564ad812b09062633ffc48f44b76328efe3832c021651af86b14"
metafile = true
