hash-format = "sha256"

[[files]]
file = ".minecraft/configureddefaults/README.md"
hash = "7d856d3f9655abc661ac67b450a0c956bbf80323786b407301fbdca02d2c5b8b"

[[files]]
file = ".minecraft/configureddefaults/config/betterf3.json"
hash = "512f6d274b00bedc700ec8e74ce83e696664f0d9f4c697b1b41a89a69da8f9b5"

[[files]]
file = ".minecraft/configureddefaults/config/minihud.json"
hash = "95149baa5c0711350998a21e230cbf9b0ca9d1be46fc87d3cdd35929e508558b"

[[files]]
file = ".minecraft/configureddefaults/config/sodium-extra-options.json"
hash = "d07d8ae3280fff966dc3bca2d7cec1e70b944b23b8c61d345d91399e15948f8a"

[[files]]
file = ".minecraft/configureddefaults/config/sodium-options.json"
hash = "81beb3f57abbd189da64708f8436d9568d816278b08c4883a1c6151c9e69d184"

[[files]]
file = ".minecraft/configureddefaults/config/voxy-config.json"
hash = "601504f04f4a45aef3e04f6c8f927921159c37faab5029ed5d4a7d71b3d9a7d3"

[[files]]
file = ".minecraft/configureddefaults/config/zoomify.json"
hash = "60a78fe1b271ce9b53e295235eb5a7cdb3a8692ca583fdaa7f5bc09f9049e2f4"

[[files]]
file = ".minecraft/configureddefaults/hotbar.nbt"
hash = "5167f62115690e38d02d08c9bf87c5b4900b5bdcc29a253de77e477c66c4e0ee"

[[files]]
file = ".minecraft/configureddefaults/icon.png"
hash = "bf6ae7e3618e9bcd7fca35f43ed4001f396734bdd1c0548fba90b483d91bcfae"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.core.config"
hash = "100a1bfb658093d203033a0b83e3757d8182ade733cf953cfbaa216e23018ef2"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.fullmap.config"
hash = "d69c664aee3818c283283d635f3c570e516e207be74abc5e63869bee1d82859b"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.minimap.config"
hash = "f67a65fdd7b2799365dfb1f0fc1e25296089032b3653628231afecb1c4ac13b7"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.minimap2.config"
hash = "dc44acf211f9942241b6882b9f5dfa2a92557c9adedc6a2ed622bf6ba28fc653"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.waypoint.config"
hash = "7287dec673c3f9a35552561364163420f5eb7a4849cd4e3a7cafe6191210b38f"

[[files]]
file = ".minecraft/configureddefaults/journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = ".minecraft/configureddefaults/journeymap/server/6.0/journeymap.server.default.config"
hash = "55a7dcffc836d0ab16a9c24ed06f5aebb7cc93c3f16b2d52c821090866958bb3"

[[files]]
file = ".minecraft/configureddefaults/journeymap/server/6.0/journeymap.server.global.config"
hash = "6f17596012f9e1b4745bd29fe25d7c4e9d212e4cde6451f737dc2afe0441f072"

[[files]]
file = ".minecraft/configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~overworld.config"
hash = "c4f3b8db82ef017cb0d85806a2f12d6e0e240feb6ac582eb2050ce2bc027f2f3"

[[files]]
file = ".minecraft/configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~the_end.config"
hash = "05e11170b8375bfa0c184d8848e27688907b99d7e5052c70d7e0e98144d45052"

[[files]]
file = ".minecraft/configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~the_nether.config"
hash = "d59cbe25cd1703999467943f7f5dc1e3ae63af8ea36bfd3913897d0b7cb92f67"

[[files]]
file = ".minecraft/configureddefaults/options.txt"
hash = "564093493410fc9da2e29a6870b344bed2271813fa764227246c22f53c0ba365"

[[files]]
file = ".minecraft/configureddefaults/resourcepacks/Faithful 64x - September 2025 Release.zip"
hash = "3e49ac823a44c92fa22d2dfec714f0ba7ddff19f6c0525f69c21897c8d926a59"

[[files]]
file = ".minecraft/configureddefaults/servers.dat"
hash = "9bcd77b4adc50ca8c5cf74110314efaf99a184b7bdbe2ad62f52756f561ad955"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "24089d7ee8d76b9983a24b6814fcd54c4387beb42eea1aeb98f37845b1b61950"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "1544978c421b6712ec7257bb5223bfd735e93184217316baff547218abe2f359"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "19ce5dae97ee068f5a37477ada773320a6b7f01838bf156421b91b4bf0dfb46c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "05de22b45d869f89f9e6e440d79318f8dd4583148f7547061b162631641eafaa"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "4155473dbb2a223450b1613e3cc90407b35edd6300cb8a921792ec1b64f4c6a7"
metafile = true

[[files]]
file = "mods/dine.pw.toml"
hash = "f445155fa3359641568c84c4adc9b3bad1a6b943a18a2d15e7629cec3e0b21be"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "752564128ccd3ef6f974f33525bd07caab2b7a09d68075b41fb24c01279f1c6f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "141f986eb6c90358ef0f37b69c7aad6ed536d864f8ac640a195912af4caaa22e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "702e47a5e68e28c0cd503b0e23951a397085a9c09cfaaf17828b6b557d8b4727"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "05ad597a123ace5c5817e822df8aa87838e8aaeedafc1211b46ae088851e9aec"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "a949197a618e5d5dca48ae2596eaa39de149e797fa9e5f7653558f973fde30e9"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "9add50ae533c11c5433a5fdfc6a816ba279a9ca39296c24b10425313d22286e7"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b523b69b247bb6947cc1c5e79be15d0952cef45e081e3c45734c595bc8de4d37"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "62cf74c52fe5b75c0599326d6f2a429ed03d19ca5dc480106ea5813d5fbddbc8"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "4696a906721a0a43006a9c7c2f4953d27e659124f047cab53554008b1ef82ae1"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "17b52c25d99245d688a22f841f786fea1ce3b7c3291393009c1d0650221df317"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "3c4a3932725de37c37c240d0639390132dc5e96831a8ef494c1be52207df9d51"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "481acb6ee66b2a8de7dc3259ccd6417d2bbd49ae979b0e252e81c4ef33a4a0b3"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "29f34999cbdb0bdd5dcd295cb13aab31c430c812ad813aa07c0783ffc7713a35"
metafile = true

[[files]]
file = "mods/packwiz-server-updater.pw.toml"
hash = "84000c7211c73647cdd2fad0c266c75abd2130de2bb4172055d9fed75d654e5e"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "c7cc3907e7adb7b30249dc2b5ccd3e30111d562475087e0188f00fb3bc5837de"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "3dbfc1ea96217a6b93c379b25b466793db08dfc0abb23cd69d129f682521ff24"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "8b36e23d92691383f5b07a30fb32208b18ecea9b9888070d071b295736b1a84b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "2a85a222f3931ea500c901293ce96ddbe7031d277e6fc8f0b49bcd651bc8be84"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e12bbb39965d413f340f8e84f747bf14780bedc2ce84f41872fc7c7dc9bc40c9"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "91d8346bf3a71cb7acd3391cd61b311784e62335e36cfae01d007a1656683a2b"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "97081fa9186296a9bae7783751f64750582abf6d690b6fbcf54b58911f905e00"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "34c8d02e5e9763aeaec0b61e27b59ce055e77705f1717e9101bcd8a35d6fbc30"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "b5c92336597cc7a560d44b6daf6c5a647c29a50249cf1872dafa496e3078565c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "b7a63b9369226baa5890f88b3e28efd24e5dfe3faacbd9b7667f1b8a4f24a253"
metafile = true
