hash-format = "sha256"

[[files]]
file = "configureddefaults/README.md"
hash = "7d856d3f9655abc661ac67b450a0c956bbf80323786b407301fbdca02d2c5b8b"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.core.config"
hash = "100a1bfb658093d203033a0b83e3757d8182ade733cf953cfbaa216e23018ef2"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.fullmap.config"
hash = "d69c664aee3818c283283d635f3c570e516e207be74abc5e63869bee1d82859b"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.minimap.config"
hash = "f67a65fdd7b2799365dfb1f0fc1e25296089032b3653628231afecb1c4ac13b7"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.minimap2.config"
hash = "dc44acf211f9942241b6882b9f5dfa2a92557c9adedc6a2ed622bf6ba28fc653"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.waypoint.config"
hash = "7287dec673c3f9a35552561364163420f5eb7a4849cd4e3a7cafe6191210b38f"

[[files]]
file = "configureddefaults/journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = "configureddefaults/journeymap/server/6.0/journeymap.server.default.config"
hash = "55a7dcffc836d0ab16a9c24ed06f5aebb7cc93c3f16b2d52c821090866958bb3"

[[files]]
file = "configureddefaults/journeymap/server/6.0/journeymap.server.global.config"
hash = "6f17596012f9e1b4745bd29fe25d7c4e9d212e4cde6451f737dc2afe0441f072"

[[files]]
file = "configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~overworld.config"
hash = "c4f3b8db82ef017cb0d85806a2f12d6e0e240feb6ac582eb2050ce2bc027f2f3"

[[files]]
file = "configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~the_end.config"
hash = "05e11170b8375bfa0c184d8848e27688907b99d7e5052c70d7e0e98144d45052"

[[files]]
file = "configureddefaults/journeymap/server/6.0/journeymap.server.minecraft~the_nether.config"
hash = "d59cbe25cd1703999467943f7f5dc1e3ae63af8ea36bfd3913897d0b7cb92f67"

[[files]]
file = "configureddefaults/resourcepacks/Faithful 64x - September 2025 Release.zip"
hash = "3e49ac823a44c92fa22d2dfec714f0ba7ddff19f6c0525f69c21897c8d926a59"

[[files]]
file = "configureddefaults/servers.dat"
hash = "9bcd77b4adc50ca8c5cf74110314efaf99a184b7bdbe2ad62f52756f561ad955"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1502d3ac2c2ce4d3dc4c2db6ca6e95fb2a5d4a279e6e1413f6c427be222887a0"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "d1eb0dbf966090d95b6658a1ded6580b0e2afc73f4bd1d1bff8b9433050068ac"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "59658f3b9d3b86b24440008fd2031c53d538cbb35e84524bcdbc67f0de7ea251"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "0fc46535baa2b4d05786d64803e0161e2ec2e408d0337e047ff81543ac8f0eaa"
metafile = true

[[files]]
file = "mods/dine.pw.toml"
hash = "9bc273d7e8139c973608f4556608e36e271f309d5a8fcc075322bcc4b20fe43d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "9d12f51a932b25751b7595ca46439a30bee2c26bf6d9913ccc9a27ade1972f36"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "eea37b6a60c019badb137a3e682461cab98ff7cb2e676620cb9fd649d21971d4"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "bda12a83dc36c4a8e5b45438700b54bf21c182d923f7f8255570893628281e06"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "4e67580688464bd3e7065f96da1fba23cc593e0a7eabd8b0522c6d82129fc6ec"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "a533c05d98c59436819e9c801198a989c6ff55133c95281ea7f8d28a71e23777"
metafile = true

[[files]]
file = "mods/packwiz-server-updater.pw.toml"
hash = "ac5a21515f286204ed7e05d1e6890897ad3055f0077974d7af69aaf26e874ff5"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "81cc0f80816be9c95b82354d4e1aaee5818513795f706e403ff93c063d3601ad"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "40851322be130d051190af0a939c36799d676e94c1ae3e555eacefe1ff28648c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "bb7064282571976ed2bbe266bcf5e525d6d661aeea89649e4d604327973cf92d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "715b86d4669a9f6b7416bbc6545bc4abd1d2ddda401be261b29fb7a1199f9f2d"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "bf28e86461c3432453a76380c44dd3c79e5c7a0644c897c3c0d984f711f351ed"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dba564c761870715c46e527e182ece9d0c50ae96c8c4e3af3f2b567e2816565d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e71ac6769675de1d2338a13e116f2aefcc8965ab0bc18b75a53572531c1447dd"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true
