name = "Echo Siege"
author = "Chrissy_Goddess"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7747402ad54f1accd6b9481d59e78de490e150ccf20dbe5ab18e38ec7e376ea"

[versions]
fabric = "0.17.2"
minecraft = "1.21"