name = "Echo Siege"
author = "Chrissy_Goddess"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8e05294d2b124efbfd3c7df99c7331ae5b1c99b6363885280d66f2e4be8f98"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21"]
