name = "Echo Siege"
author = "Chrissy_Goddess"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b63de09d64010a804d7aa0493e488d3bed25ee2abb489cbfd2515b61027b6d2"

[versions]
fabric = "0.17.2"
minecraft = "1.21"
